### ISSUE TITLE
how did you accomplish to disable nix channels knowing its $NIX_PATH issue?

### ISSUE THREAD

**Issue by RoadRoller01** [stephen-huan/nixos-config#1]
https://github.com/NixOS/nixpkgs/issues/261239
you already submitted an issue about it, so how 
did you accomplish to get around the issue?

my problem is with that `nix-shell` command stop working even if i set nix_path to the correct path. 

https://github.com/stephen-huan/nixos-config/blob/4272a2c47b386ce027a1f12f45ea9fcabcd3930a/nixos/nix.nix#L5

**Comment by stephen-huan** [comment]
This is a known issue, see https://github.com/NixOS/nix/issues/8890 and the tracking issue https://github.com/NixOS/nix/issues/9574. See also the table https://github.com/NixOS/nix/pull/9066.

As I mentioned in the issue, one has to use `-I nixpkgs=<path>` rather than `NIX_PATH=nixpkgs=<path>`. For example,

```sh
nix-shell -I nixpkgs=flake:nixpkgs -p python3
```

should just work. @RoadRoller01 does this fix your issue?

P.S. I'm happy to answer questions but it may be more efficient to ask on the help category in the [NixOS Discourse](https://discourse.nixos.org/c/learn/9) and ping [me](https://discourse.nixos.org/u/vazae/); that way people other than me can also respond and you'll get a faster response.

**Comment by RoadRoller01** [comment]
> should just work. @RoadRoller01 does this fix your issue?

yeah but i thought that you have a better solution because its harsh to add `-I ...` on every time you use `nix-shell`,
also its seems like you don't have an alias to the bla bla bla extra arguments, so are just adding them every time that 
you using `nix-shell`? 



 

> P.S. I'm happy to answer questions but it may be more efficient to ask on the help category in the [NixOS Discourse](https://discourse.nixos.org/c/learn/9) and ping [me](https://discourse.nixos.org/u/vazae/); that way people other than me can also respond and you'll get a faster response.

okey

**Comment by stephen-huan** [comment]
Since I also have the flake registry system disabled,

https://github.com/stephen-huan/nixos-config/blob/67065bc6fbadd8e7a7695f81a1a181920d20d00b/home/nix.nix#L4-L6

I don't use `-I nixpkgs=flake:nixpkgs`. Instead, I have a shell script that gets the path to nixpkgs like

```sh
#!/run/current-system/sw/bin/sh

flake="$HOME/.config/home-manager"
# `--impure` as the flake may be dirty and considered unlocked
# error: cannot call 'getFlake' on unlocked flake reference
nix eval --impure --raw \
  --expr "(builtins.getFlake \"$flake\").inputs.nixpkgs.outPath"
```

which I call `nixpkgs`. Then I use it like

```console
nix-shell -I nixpkgs=$(nixpkgs) -p python3
```

or even more concisely, with the new CLI,

```console
nix shell $(nixpkgs)#python3
```

You could also make a shell alias if you would like, but I add it every time.

**Comment by stephen-huan** [comment]
I forgot I wrote about this already at <https://dotfiles.cgdct.moe/nix/nixos/#removing-channels-and-flake-registries>.
